### ISSUE TITLE
fix formatting of the dasher filter page

### ISSUE THREAD

**Issue by rbouqueau** [gpac/wiki#2]
https://wiki.gpac.io/Filters/dasher/

It explicitely displays a star ('*'). It also seems that some list items are in italic while some others aren't.

![image](https://github.com/gpac/wiki/assets/1917976/d88ba499-e15e-4763-8563-ba54b4e23231)

**Comment by nlsdvl** [comment]
@rbouqueau I confirm this behavior is not specific to the dasher page. 

The problem with lists is mostly due to **new lines not being rendered as hard breaks**. 
As a result, rendering of the list is not triggered, and asterisks are understood as italic/em by the mardown parser.

This doesn't render a list as expected:
```
lorem ipsum:
* item1
* item2
* item3
```

while this does:
```
lorem ipsum:

* item1
* item2
* item3
```

There's an extension to python markdown that offers this behavior: [nl2br](https://python-markdown.github.io/extensions/nl2br/). 
I gave it a try without luck so far. While is [not listed by materials for mkdocs as a supported extension](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/). 

Looking for an explanation and a solution on the parser/renderer : 
- https://github.github.com/gfm/#example-282
- https://github.com/mkdocs/mkdocs/issues/1835


There is also another issue with lists in the documentation, **nested lists**:
Often there will be nested lists, for instance [here](https://github.com/gpac/wiki/blob/master/docs/Filters/dasher.md?plain=1#L338)

And it seems these aren't rendered as nested, neither [on the new wiki](https://wiki.gpac.io/Filters/dasher/?h=dasher#multiplexer-development-considerations), nor [on the old one](https://github.com/gpac/gpac/wiki/dasher#multiplexer-development-considerations). In that case the markdown content needs to be fixed.
